pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    // Installer pandas
                    bat '"F:\\python 3.12\\python.exe" -m pip install pandas'
                    
                    // Exécuter le script Python
                    bat '"F:\\python 3.12\\python.exe" data_analysis.py'
                }
            }
        }
    }
}
